# Use an official PyTorch image as the parent image
FROM pytorch/pytorch

# Set the working directory in the container to /app
WORKDIR /app

# Install system dependencies required for building Python packages
RUN apt-get update && \
    apt-get install -y build-essential python3-dev cmake unzip && \
    rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /app
COPY . /app

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Load the files from google drive
RUN gdown --id 1iIJVZmgFEkY_impLrqoUiCSdLXAtz8Sl -O /app/rec_imdb.ann
RUN gdown --id 1daFF6vmUfS8A7-y8Me1rTDW0BvYugGho -O /app/df_features_paths.csv
RUN gdown --id 1enhDYIsUmkZYurcitHWQN7FGvUjltPGv -O /app/movies-posters.zip

# For the dataset - to be able to plot movies' posters
RUN unzip movies-posters.zip && rm movies-posters.zip

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run the API app when the container launches
CMD ["python", "code/make_rec_api.py"]
