version: '3'
services:
  flask-api-service:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: flask-api-container
    ports:
      - "5000:5000"  # Expose le port 5000 de Flask
    restart: unless-stopped

  gradio-app-service:
    build:
      context: .
      dockerfile: Dockerfile-gradio
    container_name: gradio-app-container
    depends_on:
      - flask-api-service  # Gradio dépend de Flask
    ports:
      - "7860:7860"  # Expose le port 7860 de Gradio
    restart: unless-stopped

  