
# Use an official Pytorch image as the parent image
FROM pytorch/pytorch

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install system dependencies required for building Python packages
RUN apt-get update && apt-get install -y build-essential

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Download weights using gdown
RUN gdown --id 1v8HQ7I73EaHHPfw5D1ScLzlwt3M4dhAr -O /app/code/movies_filtered_df.csv
RUN gdown --id 1iVtAg66aoLW5DrklfqaurYqJ1pIveaP9 -O /app/code/bert_movies_annoy_index.ann

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run the API app when the container launches
CMD ["python", "code/rec_api.py"]
