# Use an official Pytorch image as the parent image
FROM pytorch/pytorch

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install system dependencies required for building Python packages
RUN apt-get update && apt-get install -y build-essential

# Install any needed packages specified in requirements.txt 
RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r requirements.txt 

# Make port 7860 available to the world outside this container
# Gradio by default runs on port 7860
EXPOSE 7860

# Run the Gradio app when the container launches
CMD ["python", "code/rec_gradio.py"]
