version: '3'
services:
  flask-api-service:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: flask-api-container
    ports:
      - "5000:5000"  
    restart: unless-stopped

  gradio-app-service:
    build:
      context: .
      dockerfile: Dockerfile-gradio
    container_name: gradio-app-container
    depends_on:
      - flask-api-service   # Depends on the API
    ports:
      - "7860:7860"
    restart: unless-stopped

  