
# Use an official Pytorch image as the parent image
FROM pytorch/pytorch

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Download weights using gdown
RUN gdown --id 1qZOywi8zHkkOPswdIZZu7IP97LFlv16E -O /app/code/resnet18_weights.pt
RUN gdown --id 1yoJ5qZKaYAa-pX4cMmS9liYwD4_sOeOa -O /app/code/anomaly_model.pkl

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run the API app when the container launches
CMD ["python", "code/predict_api.py"]
